### PR TITLE
switch to aiohttp

### PR DESCRIPTION
**Pull request by A-UNDERSCORE-D**
This also, because Im bad, has some reformatting, likely best to just check ahttpd.py and main

### CODE REVIEW

**Comment by jesopo** [comment]
reformat in a second PR? :P

**Comment by A-UNDERSCORE-D** [comment]
> reformat in a second PR? :P

Its really a pain to get that right as things are configured to reformat files as I go

**Comment by jesopo** [comment]
that sounds like a configuration problem

**Comment by A-UNDERSCORE-D** [comment]
> that sounds like a configuration problem

Except that its exactly how an IDE should be configured. I shouldnt have to worry about code formatting.

**Comment by jesopo** [comment]
as a rule of thumb, you shouldn't be making PR with compound changes. makes it impossible to review

**Comment by A-UNDERSCORE-D** [comment]
Ive removed the formatting on the file I didnt touch, I'd have to redo the entire PR to remove it elsewhere.

**Comment by A-UNDERSCORE-D** [comment]
> as a rule of thumb, you shouldn't be making PR with compound changes. makes it impossible to review

Correct, generally. And I apologize for that. However all our stuff should be autoformatted anyway. I have some waiting PRs elsewhere for that as you've asked.

**Comment by jesopo** [comment]
I don't know that I agree that our projects should all be autoformatted. perhaps a topic of eng meeting

**Comment by A-UNDERSCORE-D** [comment]
> I don't know that I agree that our projects should all be autoformatted. perhaps a topic for an eng meeting

Theres... zero reason to not have consistent formatting. 
But Im sure that I can push it to a dev meeting until then. However I do not want to redo a PR now. I created #6  which if you merge it should reduce churn here.

**Pull request merged**
